config/routes.rb
DemoTable::Application.routes.draw do
  resources :data_tables do
  
    collection do
      get :prepare_data
      get :proxy
      delete 'bulk_delete', action: :bulk_delete
    end
    
    get :prepare_data, on: :collection
    get :prepare_pivot, on: :collection
  end

   root :to => 'data_tables#index'

end

app/models/data_table.rb
class DataTable < ActiveRecord::Base
  self.table_name = 'data_tables'
  attr_accessible :age, :first_name, :id, :last_name, :position, :salary, :starting_work

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @data_tables }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @data_table }
    end
  end

  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @data_table }
    end
  end

  def edit
    @data_table = DataTable.find(params[:id])
  end

  def create
    @data_table = DataTable.new(params[:data_table])

    respond_to do |format|
      if @data_table.save
        format.html { redirect_to @data_table, notice: 'Data table was successfully created.' }
        format.json { render json: @data_table, status: :created, location: @data_table }
      else
        format.html { render action: "new" }
        format.json { render json: @data_table.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @data_table = DataTable.find(params[:id])

    respond_to do |format|
      if @data_table.update_attributes(params[:data_table])
        format.html { redirect_to @data_table, notice: 'Data table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @data_table.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @data_table = DataTable.find(params[:id])
    @data_table.destroy

    respond_to do |format|
      format.html { redirect_to data_tables_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/data_tables_controller.rb
class DataTablesController < ApplicationController
  before_filter :prepare_filter_query, :create_paginate_variables, :prepare_filter_sort_array, :only => :prepare_data

  # GET /data_tables
  # GET /data_tables.json
  def index
    @data_tables = DataTable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @data_table }
    end
  end

  # GET /data_tables/1
  # GET /data_tables/1.json
  def show
    @data_table = DataTable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @data_table }
    end
  end

  # GET /data_tables/new
  # GET /data_tables/new.json
  def new
    @data_table = DataTable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @data_table }
    end
  end

  # GET /data_tables/1/edit
  def edit
    @data_table = DataTable.find(params[:id])
  end

  # POST /data_tables
  # POST /data_tables.json
  def create
    data_table = DataTable.new(params[:data_table])

    respond_to do |format|
      if data_table.save
        format.json { render json: response_hash(data_table), status: :created }
      else
        format.json { render json: data_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /data_tables/1
  # PUT /data_tables/1.json
  def update
    data_table = DataTable.find(params[:id])

    respond_to do |format|
      if data_table.update_attributes(params[:data_table])
        format.json { render json: response_hash(data_table) }
      else
        format.json { render json: data_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_tables/1
  # DELETE /data_tables/1.json
  def destroy
    data_table = DataTable.find(params[:id])
    data_table.destroy

    respond_to do |format|
      format.json { render json: response_hash }
    end
  end

  def bulk_delete
    DataTable.where(id: params[:ids]).delete_all

    respond_to do |format|
      format.json { render json: response_hash }
    end
  end

  def prepare_pivot
    @pivot_hash = {}
    @search = DataTable.limit(100)
    pivot_table = @search

    pivot = []
    pivot_table.each do |p|
      pivot.push({
          "id" => p.id,
          "first_name" => p.first_name,
          "last_name" => p.last_name,
          "age" => p.age,
          "position" => p.position,
          "starting_work" => p.starting_work,
          "salary" => p.salary
      })
    end

   @pivot_hash = pivot
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pivot_hash }
    end
  end

  def prepare_data
    @table_hash = {}
    @search = DataTable.ransack(@filter)
    @search.sorts = @sort
    data_table = @search.result.paginate(page: @page, per_page: @per_page)

    data = []
    data_table.each do |d|
      data.push({
         "id" => d.id,
         "first_name" => d.first_name,
         "last_name" => d.last_name,
         "age" => d.age,
         "position" => d.position,
         "starting_work" => d.starting_work,
         "salary" => d.salary
     })
    end

    # Devexpress data count for paginate
    total_count = { "totalCount" => data_table.count } # if params[:requireTotalCount].present?
    summary = { "summary" => [data_table.count, (data_table.sum(:salary) rescue DataTable.sum(:salary))] }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: response_hash(data, {}, {}, total_count, summary) }
    end
  end

  private

  def prepare_filter_query
    matcher = ""
    find_search = ""
    @filter = {}

    (JSON::parse(params[:filter]) rescue []).each do |value|
      if value.kind_of?(Array)
        matcher += value.first + "_" rescue next
        find_search = value.last
      else
        matcher += value + "_" rescue next
      end
    end

    unless matcher.blank?
      matcher += "cont"
      @filter[matcher] = find_search
    end

  end

  def prepare_filter_sort_array
    @sort = []
    (JSON::parse(params[:sort]) rescue []).each do |value|
      sort_val = value["selector"] + " " + (value["desc"] ? "desc" : "asc")
      @sort.push(sort_val)
    end
  end

  def create_paginate_variables
    @page = params[:skip].to_i == 0 ? 1 : (params[:skip].to_i / params[:take].to_i) + 1
    @per_page = params[:take].to_i
  end

  def response_hash(data = {}, success = {}, error = {}, *args)
    response = {
        "data" => data,
        "success" => success,
        "error" => error
    }
    args.compact.each do |arg|
      response.merge!(arg)
    end

    response
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_tables_helper.rb
module DataTablesHelper
end

app/views/data_tables/_form.html.erb
<%= form_for(@data_table) do |f| %>
  <% if @data_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_table.errors.count, "error") %> prohibited this data_table from being saved:</h2>

      <ul>
      <% @data_table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :starting_work %><br />
    <%= f.date_select :starting_work %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.number_field :salary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_tables/edit.html.erb
<h1>Editing data_table</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_table %> |
<%= link_to 'Back', data_tables_path %>

app/views/data_tables/index.html.erb
<script>
    //let employees = <%= raw @table_hash.to_json %>;
</script>


<div id="content" style="display: flex;">
  <div class="demo-container" style="width:80%;">
    <div id="data-grid-demo">
      <div id="gridDeleteSelected"></div>
      <div id="gridContainer" style="padding: 0;"></div>
    </div>
    <div id="sales" style="margin-top: 46px;"></div>
    <div id="context-menu"></div>
  </div>

  <div style="width: 20%;">
    <div style="border: 1px solid #dddddd;height: calc(100% - 58px);margin-top:46px;background-color: #ffffff;">
      <div id="pivot-mode-radio" style="margin: 10px;">

      </div>
      <div class="container">
        <div id="sales-fieldchooser" style="width: 100% !important; height: 100% !important;"></div>
      </div>
    </div>
  </div>
</div>

app/views/data_tables/new.html.erb
<h1>New data_table</h1>

<%= render 'form' %>

<%= link_to 'Back', data_tables_path %>

app/views/data_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @data_table.id %>
</p>

<p>
  <b>First name:</b>
  <%= @data_table.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @data_table.last_name %>
</p>

<p>
  <b>Age:</b>
  <%= @data_table.age %>
</p>

<p>
  <b>Position:</b>
  <%= @data_table.position %>
</p>

<p>
  <b>Starting work:</b>
  <%= @data_table.starting_work %>
</p>

<p>
  <b>Salary:</b>
  <%= @data_table.salary %>
</p>


<%= link_to 'Edit', edit_data_table_path(@data_table) %> |
<%= link_to 'Back', data_tables_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoTable</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/exceljs/3.3.1/exceljs.min.js" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.min.js" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.5/jszip.min.js" %>
  <script>window.jQuery || document.write(decodeURIComponent('%3Cscript src="js/jquery.min.js"%3E%3C/script%3E'))</script>
  <%= stylesheet_link_tag    "https://cdn3.devexpress.com/jslib/19.2.7/css/dx.common.css", :media => "all" %>
  <%= stylesheet_link_tag    "https://cdn3.devexpress.com/jslib/19.2.7/css/dx.light.css", :media => "all" %>
  <%= javascript_include_tag "https://cdn3.devexpress.com/jslib/19.2.7/js/dx.all.js" %>

  <%= stylesheet_link_tag    "demo_table.css", :media => "all" %>

  <%= csrf_meta_tags %>
</head>
<body class="dx-viewport">

<%= yield %>

<%= javascript_include_tag "form/edit.js" %>
<%= javascript_include_tag "excel/excel.js" %>
<%= javascript_include_tag "data_grid.js" %>
<%#= javascript_include_tag "pivot_grid.js" %>
<%= javascript_include_tag "context_menu.js" %>

<script>
    var myVar = setInterval(myTimer, 2000);

    function myTimer() {
        document.getElementById("pivot-mode-radio").click();
        clearInterval(myVar);
    }
</script>
</body>
</html>